spring:
  application:
    name: lecture-hub

  datasource:
    url: jdbc:mysql://localhost:3306/lecture_hub
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
